### ISSUE TITLE
Use layout API

### ISSUE THREAD

**Issue by craftzdog** [yimajo/inkdrop-toggle-editor-meta-layout#1]
Hi, thanks for creating a plugin!

I found that you manually tweak the style of the meta bar [here](https://github.com/yimajo/inkdrop-toggle-editor-meta-layout/blob/main/lib/toggle-editor-meta-layout.js#L8).
Instead, you can remove the bar from the layout using [the Layout API](https://docs.inkdrop.app/reference/layout-manager).
There is "editor" layout you want to change: https://docs.inkdrop.app/reference/state-layouts#editor

A good example is https://github.com/nomnomab/inkdrop-center-editor

Can you please fix that?

**Comment by yimajo** [comment]
Thank you for your feedback and the example URL.

I understand how to use the Layout API from the example, so I started using it. PR #3

I would appreciate your feedback when you have time.

**Comment by craftzdog** [comment]
Looks great! Thanks for the quick update🙌
