### ISSUE TITLE
Save the bar visibility

### ISSUE THREAD

**Issue by craftzdog** [yimajo/inkdrop-toggle-editor-meta-layout#2]
Currently, it doesn't remember the bar visibility after relaunching the app. It'd be nice to support that :)

- Documentation: https://docs.inkdrop.app/reference/config#defining-settings-for-your-plugin
- Mermaid plugin example: https://github.com/inkdropapp/inkdrop-mermaid/blob/master/lib/index.js#L85

**Comment by yimajo** [comment]
Thank you for your feedback and the example URL. 

I tried the same as [Hide Menu Bar](https://github.com/inkdropapp/inkdrop-hide-menu-bar) in PR #3.
(It's not the mermaid way you suggested)

Maybe this will solve the problem. 
I would appreciate your feedback when you have time.

**Comment by craftzdog** [comment]
Makes sense! Now you can publish it to the plugin registry🙏
